add login
Ayushi20-19/winter-store pull request #5
Opened 2022-03-20 21:36 UTC by Ayushi20-19

<h1>FEATURE ADDED</h1>
<ul>
<li>add login page</li>
</ul>

<b> link </b> 
<b>you can skip CSS files only functionality needs to be reviewed.</b>

2022-03-21 16:56 UTC, starver20 commented on src/components/Auth/Login.js
> +
You can add a check here to see if the response status is 200, only then you shloud continue with rest of the operations.

2022-03-21 16:57 UTC, starver20 commented on src/components/Auth/Signup.js
> +        });
Same response status check is needed here

2022-03-21 16:57 UTC, starver20 commented on src/components/Auth/Signup.js
>            payload: {
I believe you are going to add the payload later

2022-03-21 16:58 UTC, starver20 reviewed
other than the suggestions rest of the code looks good.

2022-03-22 06:10 UTC, AnkurChunekar requested changes
As suggested by @starver20 for better error handling response status should be checked if it's same as expected, other than that code looks good to me.

2022-03-26 09:04 UTC, merged